In [6]:
import numpy as np

In [10]:
ls = [1,2.5,3]
print(ls)

[1, 2.5, 3]


In [13]:
arr = np.array(ls,dtype='int32')
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [12]:
arr.dtype

dtype('float64')

In [16]:
np.zeros(2,dtype='int32')

array([0, 0])

In [17]:
arr*3

array([3, 6, 9])

In [18]:
arr*arr

array([1, 4, 9])

In [21]:
ls*3

[1, 2.5, 3, 1, 2.5, 3, 1, 2.5, 3]

In [22]:
arr[0:2]

array([1, 2])

In [23]:
arr[0:]

array([1, 2, 3])

In [26]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype='int32')

In [27]:
arr1[0:3,3:5]

array([[ 4,  5],
       [ 9, 10]])

In [28]:
arr1[0][0]

1

In [29]:
arr1[0,0]

1

In [30]:
a = arr[0:2]

In [31]:
a[0] = 5

In [32]:
print(arr)

[5 2 3]


In [33]:
b=arr[0:2].copy()
b[0]=1
print(arr)

[5 2 3]


In [34]:
print(arr.transpose())

[5 2 3]


In [35]:
print(arr1.transpose())

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [36]:
np.reverse(arr1)

AttributeError: module 'numpy' has no attribute 'reverse'

In [37]:
np.flip(arr1)

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [38]:
np.flip(arr1,axis=1)

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6]])

In [40]:
arr1.reshape(1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [42]:
arr1.reshape(1,10)

array([[[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]]])

In [43]:
np.argmin(arr1)

0

In [46]:
np.argmax(arr1.reshape(1,10))

9

In [47]:
np.random.randn(2,3)

array([[ 0.59312864, -1.0992065 , -1.29818298],
       [-0.23681301,  0.14267621,  0.5649736 ]])

In [48]:
np.random.randint(3,size=5)

array([2, 1, 1, 1, 1])

In [50]:
np.random.randint(-1,2,size=10)

array([ 1,  0,  0,  1,  0, -1, -1,  0, -1,  0])